import React from "react";
import { Container, Row, Col } from "react-bootstrap";
import ProjectCard from "./ProjectCards";
import Particle from "../Particle";
import plugging from "../../Assets/Projects/Plugging.png";
import fish from "../../Assets/Projects/fish.png";
import car from "../../Assets/Projects/car.png";
import mp from "../../Assets/Projects/motion_planning.gif"
import sl from "../../Assets/Projects/SLAM.png"
import dk from "../../Assets/Projects/Door_Key.gif"
import robo from "../../Assets/Projects/robot_arm.png"
import pano from "../../Assets/Projects/panorama.png"

function Projects() {
  return (
    <Container fluid className="project-section">
      <Particle />
      <Container>
        <h1 className="project-heading">
          My <strong className="purple">Projects</strong>
        </h1>
        <p style={{ color: "white" }}>
          Here are a few projects I've worked on in UCSD and Tsinghua University.
        </p>
        <Row style={{ justifyContent: "center", paddingBottom: "10px" }}>

                  <Col md={6} className="project-card">
            <ProjectCard
              imgPath={mp}
              isBlog={false}
                          title="3D Motion Planning based on A* and RRT"
                          description1="
Program to generate a coordinate sequence of a suboptimal path in complex 3-dimension environment."
                          description2="
Implemented A* and RRT Algorithms to generate optimal control policy for a Deterministic Shortest Path problem."
                          description3="
Applied Slab method to detect collision."
                          description4="
Proved the length of path shorter than one generated by greedy algorithm."
                      />
                  </Col>

            <Col md={6} className="project-card">
            <ProjectCard
              imgPath={sl}
              isBlog={false}
                          title="Visual-Inertial SLAM System"
                          description1="
Program to rebuild a vehicle's trajectory based on data from a stereo camera and a inertial sensor."
                          description2="
Implemented Extended Kalman Filter Algorithm to build the map of visual landmarks."
                          description3="
Combined the landmark map and estimated trajectory to correct the trajectory."
                          description4="
Built a complete visual-inertial SLAM algorithm to generate landmarks along vehicle’s trajectory simultaneously on the map."
                      />
                  </Col>

            <Col md={6} className="project-card">
            <ProjectCard
              imgPath={dk}
              isBlog={false}
                          title="Dynamic Programming in Door & Key navigation"
                          description1="
Program to generate optimal action sequence for an agent to reach a known goal in a door & key grid map."
                          description2="
Applied Dynamic Programming Algorithm to generate optimal control policy for a Deterministic Shortest Path problem."

                      />
                  </Col>


            <Col md={6} className="project-card">
            <ProjectCard
              imgPath={robo}
              isBlog={false}
                          title="UR3e Robot Arm Control"
                          description1="
Program to control an UR3e robot arm, achieving desired motion in Ubuntu simulation environment."
                          description2="
Implemented forward kinematics to predict end-effector orientation."
                          description3="
Implemented PI control algorithm to calculate feedforward and feedback control."
                         />
                  </Col>

          <Col md={6} className="project-card">
            <ProjectCard
              imgPath={pano}
              isBlog={false}
                          title="Panorama Reconstruction with IMU Sensor"
                          description1="
Program to track camera's orientation and rebuild a panorama picture."
                          description2="
Tracked a rotating body’s orientation based on acceleration and angular velocity data from attached IMU sensor."
                          description3="
Applied projected gradient descent algorithm to minimize the error of estimated orientation sequence."
                          description4="
Reconstructed panoramic images by stitching RGB camera images over time based on the body orientation"
                      />

                  </Col>

                  <Col md={6} className="project-card">
                      <ProjectCard
                          imgPath={fish}
                          isBlog={false}
                          title="Bionic Fish Robot"
                          description1="
Underwater robot inspired by manta ray and squad."
                          description2="
Used all soft fins to drive the robot"
                          description3="
Set up an embedded control system based on a STM32 MCU and sent instructions via Bluetooth serial part."
                          description4="
The prototype won 2nd prize in Tsinghua University mechanical design competition."


                      />

                  </Col>
          <Col md={6} className="project-card">
            <ProjectCard
              imgPath={plugging}
              isBlog={false}
                          title="Disc Type Plugging Device for Gas Pipeline"
                          description1="
Mechanical device developed to plug gas pipeline for Beijing Gas Co., Ltd."
                          description2="
Designed a mechanical structure capable for manual operation without external power."
                          description3="
Simulated the deformation and contact pressure of the rubber disc in ANSYS
and simulated the stress in heavy-duty parts in MATLAB."
                          description4="
Prototype was accepted by the company and put into market use."
                          
                      />

                  </Col>



          <Col md={6} className="project-card">
            <ProjectCard
              imgPath={car}
              isBlog={false}
                          title="Track-tracing Automatic Vehicle"
                          description1="
Electric vehicle controlled by STM32, able to trace tracks and avoid obstacles automatically."
                          description2="
Collected road information with a 128 pixel camera and identified obstacles with 4 ultrasonic sensors."
                          description3="
Applied PID algorithm in motion planning to achieve better performance."
            />
          </Col>





     
        </Row>
      </Container>
    </Container>
  );
}

export default Projects;
